layout_spectrum: 0.02486647
typography_spectrum: 0.3957653
color:
  saturation: 0.655057
  lightness: 0.4991305
  brandStrength: 0.7065722
  rhythmicContrast: 0.2848865
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Lensjournal
